/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';

import { DemoApp as DemoApp } from './components/demo-app/demo-app';

interface HTMLDemoAppElement extends DemoApp, HTMLElement {
}
declare var HTMLDemoAppElement: {
  prototype: HTMLDemoAppElement;
  new (): HTMLDemoAppElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "demo-app": HTMLDemoAppElement;
  }
  interface ElementTagNameMap {
      "demo-app": HTMLDemoAppElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "demo-app": JSXElements.DemoAppAttributes;
      }
  }
  namespace JSXElements {
      export interface DemoAppAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}

